PUT http://localhost:3001/api/reservations/5c891fb01c9d440000a83c83
content-type: application/json

{
  "startTime": "2019-03-19T21:30:00.000Z",
  "endTime": "2019-03-19T22:45:00.000Z",
  "name": "Testi1",
  "active": false
} 