PUT http://localhost:3001/api/reservations/5c8e5babe03f3e6bb5bc1386
content-type: application/json

{
   "name": "New est with urs",
    "startTime": "2019-03-20T21:30:00.000Z",
    "endTime": "2019-03-20T22:30:00.000Z",
    "active": true,
    "id": "5c8e5babe03f3e6bb5bc1386"
} 